### ISSUE TITLE
使用这个库 要导入那么多相关联的文件进去吗？我觉得模块化一点是不是要好点。

### ISSUE THREAD

**Issue by tc1993** [pujiaxin33/JXPageListView#1]
感觉为了用个功能，要导入的东西太多了，各种引入头文件，要必须全部导入进去吗？可以分模块化一下吗？相互依赖太强了。本来以为导入PageListView文件夹下面的就够了，然而还要把JXCategoryView文件下那么多东西导进去。感觉很多东西完全没必要啊，用不到的

**Comment by pujiaxin33** [comment]
-  关于`JXCategoryView`
为了封装更简单，而且`JXCategoryView`功能足够使用，所以集成在里面了。

- 其他
类似于MBProgressHUD、MJRefresh都是demo引入的，你自己可以选择性使用

**Comment by tc1993** [comment]
好吧 我自己下载了源码 然后在里面改了些东西 以满足我的需要 比如标题字体啊。在没有导航栏的情况下的偏移量等等。现在可以用了。

**Comment by pujiaxin33** [comment]
嗯，这个效果的标准不一，也建议修改源码完成自己想要的效果。该框架算是提供一个基础和思路。

**Comment by tc1993** [comment]
嗯嗯，好的。能提供思路也是很谢谢了。自己写费时间。项目时间又比较紧。当然是有现成的比较好。还是感谢作者提供。

暴走的鑫鑫 <notifications@github.com> 于2018年10月15日周一 下午2:29写道：
