### ISSUE TITLE
发现bug

### ISSUE THREAD

**Issue by jun-hui** [pujiaxin33/JXPageListView#10]
在设置了 navigationController.hidesBarsOnSwipe = YES 的时候，会有问题
![1B910DDA-813C-4F33-8295-3293CD81A8D2](https://user-images.githubusercontent.com/23160552/64502112-e78bd700-d2f6-11e9-984b-21f5933f645b.png)
滚动到这里都正常：
![D364A2D3-A2D0-46B2-83F9-193C179AEC35](https://user-images.githubusercontent.com/23160552/64502200-3f2a4280-d2f7-11e9-99b2-8ad2f6fedef2.png)
再向上滚动一点点，就不对了:
![24284B9F-F175-469A-87CF-9918236370BF](https://user-images.githubusercontent.com/23160552/64502204-46e9e700-d2f7-11e9-9d1a-698b6a24032b.png)

**Comment by jun-hui** [comment]
@pujiaxin33 这个问题是需要改哪个地方？

**Comment by isdotjim** [comment]
搭个车...
想邀请你们来w3c.group创建项目对应的小组。w3c.group是类似知识星球的社群工具，但却不是知识付费性质的创作者社区，这里有相关的文章：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by pujiaxin33** [comment]
你是什么系统，iOS13没有问题，建议你尝试用自定义导航栏实现同样的效果

**Comment by jun-hui** [comment]
都忘了回来看问题了，无论是自定义导航栏还是系统导航栏都有这个问题

**Comment by jun-hui** [comment]
就是刚开始进入页面时，显示导航栏，网上滑动的时候动画改变导航栏高度（或者隐藏导航栏），就会发现滑动到一定位置，框架的标签栏就会闪动到上面去（正常来讲红框区域应该也是慢慢滑动到标签栏闪动后的位置去的），而且红框空白区域会停在那滑不上去了

**Comment by pujiaxin33** [comment]
建议使用https://github.com/pujiaxin33/JXPagingView作为替代，该库已不再维护了。
