### ISSUE TITLE
一个小建议

### ISSUE THREAD

**Issue by ghost** [pujiaxin33/JXPageListView#11]
老哥我发现，在mainTableView用力向上滚动时，当pinCategoryView pin在页面顶部时，页面会立即停止滚动，给人一种滚动被中断卡住的感觉，咸鱼和转转做同样的操作，他们pageview里面的tableview还是会继续向上滚的，不会中断，这样用户体验好很多。

**Comment by pujiaxin33** [comment]
请参考https://github.com/pujiaxin33/JXPagingView 里面的JXPagerSmoothView，实现了你说得效果
