### ISSUE TITLE
jxsegmentedView 如何实现这种效果

### ISSUE THREAD

**Issue by bluesky0109** [pujiaxin33/JXPageListView#12]
jxsegmentedView 如何实现这种效果

**Comment by pujiaxin33** [comment]
什么意思呢？

**Comment by bluesky0109** [comment]
> 什么意思呢？

就是 如何用 jxsegmentedView 实现 jxPageListView中的 下拉刷新、页面loading、悬浮header位置调整 这几个的效果

**Comment by pujiaxin33** [comment]
本来jxsegmentedView和jxcategoryview的功能差不多就是一样的，为什么要替换呢？

**Comment by pujiaxin33** [comment]
建议使用 https://github.com/pujiaxin33/JXPagingView 作为替代，该库已不再维护了。
