### ISSUE TITLE
上面是自定义cell，下面有很多个标签页的情况

### ISSUE THREAD

**Issue by 200895045** [pujiaxin33/JXPageListView#13]
比如下面20个标签页，listViewArray就需要创建20个view吗？有没有好点的方法？

**Comment by pujiaxin33** [comment]
这个库已经严重了落后于[JXPagingView](https://github.com/pujiaxin33/JXPagingView)库。JXPaingView已经使用懒加载创建列表了。但是JXPageListView这个库我目前没有时间更新相关逻辑了。你可以尝试自己实现一下。

**Comment by 200895045** [comment]
[JXPagingView](https://github.com/pujiaxin33/JXPagingView)可以实现这个效果吗？

**Comment by 200895045** [comment]
[JXPagingView](https://github.com/pujiaxin33/JXPagingView)可以实现这个效果吗？ @pujiaxin33

**Comment by pujiaxin33** [comment]
建议使用 https://github.com/pujiaxin33/JXPagingView 作为替代，该库已不再维护了。
