### ISSUE TITLE
配合mjrefresh的下拉刷新时，有概率页面会无法点击以及滑动

### ISSUE THREAD

**Issue by snail2736** [pujiaxin33/JXPageListView#14]
配合mjrefresh做下拉刷新，在刷新状态还没结束时切换tab，反复操作，有一定的概率tab下的页面无法上下滑动以及无法点击页面内容
版本情况
- JXCategoryView (1.5.2)
  - JXPagingView/Pager (1.2.2)
  - MJRefresh (3.3.1)

**Comment by snail2736** [comment]
看现象应该是点击滑动到了外层的collectioncell上

**Comment by pujiaxin33** [comment]
你用的是XPageListView还是JXPagingView呢？

**Comment by snail2736** [comment]
> 你用的是XPageListView还是JXPagingView呢？

用的是JXPagingView

**Comment by pujiaxin33** [comment]
建议使用 https://github.com/pujiaxin33/JXPagingView 作为替代，该库已不再维护了。
