### ISSUE TITLE
点击橡胶机关枪 想要跳转到新的控制器

### ISSUE THREAD

**Issue by lxlnihao** [pujiaxin33/JXPageListView#18]
点击橡胶机关枪跳转到新的控制器 只能通过传递把参数传到前面一个控制器 再跳转吗?可以把自定义的view换成控制器吗?该怎么做 谢谢

**Comment by pujiaxin33** [comment]
建议使用 https://github.com/pujiaxin33/JXPagingView 作为替代，该库已不再维护了。
