### ISSUE TITLE
使用的时候有时候第一次加载 会出现header

### ISSUE THREAD

**Issue by deanli08** [pujiaxin33/JXPageListView#19]

**Comment by deanli08** [comment]
header 跑到最顶部
![2061609935889_ pic](https://user-images.githubusercontent.com/11403708/103768319-3bc6d880-505d-11eb-898a-15a33c902c8f.jpg)

**Comment by pujiaxin33** [comment]
建议使用 https://github.com/pujiaxin33/JXPagingView 作为替代，该库已不再维护了。
