### ISSUE TITLE
非常感谢作者贡献代码，这是目前我觉得最好的方案，很好的帮助了我！

### ISSUE THREAD

**Issue by RexDu** [pujiaxin33/JXPageListView#2]
请问可以加一个TopMargin吗？就是可以指定切换栏距离顶部的高度，方便控制悬停的位置？

**Comment by RexDu** [comment]
![WechatIMG2](https://user-images.githubusercontent.com/4757837/54201378-736ba480-4508-11e9-9e4b-f3cfdb10fab4.png)
或许这个图能表达清楚我的意思，不知道加起来是否方便？

**Comment by pujiaxin33** [comment]
能明白你的意思，但是我需要研究一下能否可行

**Comment by RexDu** [comment]
> 能明白你的意思，但是我需要研究一下能否可行

我读了一下您的代码，高度计算那边确实比较多的边界值，但代码蛮清晰的，您加的话应该也很快》
确实很棒的框架~

**Comment by pujiaxin33** [comment]
已经添加了pinSectionHeaderVerticalOffset属性，最新仓库可测
