### ISSUE TITLE
JXPagerListContainerView 如何设置宽度

### ISSUE THREAD

**Issue by YelCode** [pujiaxin33/JXPageListView#3]
用的是悬停的效果
底下的tableview 也就是JXPagerListContainerView 如何设置宽度？

**Comment by pujiaxin33** [comment]
里面写死和屏幕等宽的

**Comment by YelCode** [comment]
嗯嗯 感谢回复
已经改源码了 在cellforrow改的
多出一个cellcolor 和左边距
