### ISSUE TITLE
JXPagingListContainerView崩溃

### ISSUE THREAD

**Issue by Answer000** [pujiaxin33/JXPageListView#5]
JXPagingListContainerView的  func deviceOrientationDidChanged() 偶尔会崩溃，bounds = .zero时

**Comment by pujiaxin33** [comment]
你说的是JXPagingView这个库吗？有崩溃截图吗？

**Comment by pujiaxin33** [comment]
确实有这个可能性，JXPagingView 1.1.8版本会修复

**Comment by Answer000** [comment]
> 你说的是JXPagingView这个库吗？有崩溃截图吗？

没有截图，就是bound = .zero的时候，分母就会等于0，会直接导致崩溃，建议做一下判断

**Comment by Answer000** [comment]
请问你能尽快改一下这个问题吗？因为项目中有用到这个库，而且奔溃频率还比较高

**Comment by pujiaxin33** [comment]
正在更新1.1.8的包，稍等一会儿，网络比较慢，应该要10几分钟

**Comment by pujiaxin33** [comment]
再强调一下，我说的是这个库：https://github.com/pujiaxin33/JXPagingView

**Comment by pujiaxin33** [comment]
🎉  Congrats

 🚀  JXPagingView (1.1.8) successfully published
 📅  May 24th, 04:09
 🌎  https://cocoapods.org/pods/JXPagingView
 👍  Tell your friends!

记得 pod repo update 一下哟
