### ISSUE TITLE
mainTableView 设置为UITableViewStyleGrouped

### ISSUE THREAD

**Issue by deanli08** [pujiaxin33/JXPageListView#6]
JXPageListView 里面的mainTableView 设置为UITableViewStyleGrouped  话 有问题默认会上移
![image](https://user-images.githubusercontent.com/11403708/62116916-977c2680-b2ed-11e9-9525-68a3c435c838.png)

**Comment by deanli08** [comment]
@pujiaxin33

**Comment by pujiaxin33** [comment]
不能设置为UITableViewStyleGrouped，只能设置为UITableViewStylePlain，主要是为了悬浮header

**Comment by illusionspaces** [comment]
为什么不能设置为group，因为计算不出来吗

**Comment by pujiaxin33** [comment]
因为要利用UITableViewStylePlain风格，sectionHeader悬浮的效果哈

**Comment by illusionspaces** [comment]
如果是group类型的table有解决方案吗

**Comment by pujiaxin33** [comment]
目前没有，你可以在视觉上面用UITableViewStylePlain仿造出UITableViewStyleGrouped的样式，比如用自定义cell替换sectionHeader

**Comment by illusionspaces** [comment]
好的，多谢
